/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as merkleDistributorSol from "./MerkleDistributor.sol";
export type { merkleDistributorSol };
import type * as testtSol from "./Testt.sol";
export type { testtSol };
export type { Presale } from "./Presale";
export type { PresaleV2 } from "./PresaleV2";
export type { TinToken } from "./TinToken";
export type { USDTToken } from "./USDTToken";
