/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as merkleDistributorSol from "./MerkleDistributor.sol";
export * as testtSol from "./Testt.sol";
export { Presale__factory } from "./Presale__factory";
export { PresaleV2__factory } from "./PresaleV2__factory";
export { TinToken__factory } from "./TinToken__factory";
export { USDTToken__factory } from "./USDTToken__factory";
