/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "ERC20Burnable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20Burnable__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "MerkleDistributorTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleDistributorTest__factory>;
    getContractFactory(
      name: "Presale",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Presale__factory>;
    getContractFactory(
      name: "PresaleV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PresaleV2__factory>;
    getContractFactory(
      name: "MerkleTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MerkleTest__factory>;
    getContractFactory(
      name: "TinToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TinToken__factory>;
    getContractFactory(
      name: "USDTToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.USDTToken__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "ERC20Burnable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20Burnable>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "MerkleDistributorTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleDistributorTest>;
    getContractAt(
      name: "Presale",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Presale>;
    getContractAt(
      name: "PresaleV2",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.PresaleV2>;
    getContractAt(
      name: "MerkleTest",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MerkleTest>;
    getContractAt(
      name: "TinToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TinToken>;
    getContractAt(
      name: "USDTToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.USDTToken>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
