/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as openzeppelin from "./@openzeppelin";
export type { openzeppelin };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { Ownable } from "./@openzeppelin/contracts/access/Ownable";
export { Ownable__factory } from "./factories/@openzeppelin/contracts/access/Ownable__factory";
export type { ERC20 } from "./@openzeppelin/contracts/token/ERC20/ERC20";
export { ERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/ERC20__factory";
export type { ERC20Burnable } from "./@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable";
export { ERC20Burnable__factory } from "./factories/@openzeppelin/contracts/token/ERC20/extensions/ERC20Burnable__factory";
export type { IERC20Metadata } from "./@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata";
export { IERC20Metadata__factory } from "./factories/@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata__factory";
export type { IERC20 } from "./@openzeppelin/contracts/token/ERC20/IERC20";
export { IERC20__factory } from "./factories/@openzeppelin/contracts/token/ERC20/IERC20__factory";
export type { MerkleDistributorTest } from "./contracts/MerkleDistributor.sol/MerkleDistributorTest";
export { MerkleDistributorTest__factory } from "./factories/contracts/MerkleDistributor.sol/MerkleDistributorTest__factory";
export type { Presale } from "./contracts/Presale";
export { Presale__factory } from "./factories/contracts/Presale__factory";
export type { PresaleV2 } from "./contracts/PresaleV2";
export { PresaleV2__factory } from "./factories/contracts/PresaleV2__factory";
export type { MerkleTest } from "./contracts/Testt.sol/MerkleTest";
export { MerkleTest__factory } from "./factories/contracts/Testt.sol/MerkleTest__factory";
export type { TinToken } from "./contracts/TinToken";
export { TinToken__factory } from "./factories/contracts/TinToken__factory";
export type { USDTToken } from "./contracts/USDTToken";
export { USDTToken__factory } from "./factories/contracts/USDTToken__factory";
